services:
  postgres:
    image: postgres:latest
    container_name: ToDoList-postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: some
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
   postgres_data: