spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: some
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
